### ISSUE TITLE
"division by zero" error

### ISSUE THREAD

**Issue by miligeo18** [theislab/scCODA#23]
Hello, 

I am working with a single cell data set with 12 clusters and 3 treatment conditions (including the control). For a couple different cell types I've tried to set as the reference, I get a division by zero error after running model_obj_iggvsnat.sample_hmc() . I am not sure why this happens when I set certain cell types as the reference, but not with others. 

There have also been some instances where I have run the code based on the getting started tutorial, and received results, but then have had the "division by zero" error when reruning the same code without changing the reference cell type or anything else. 

Any insights into what might be going on here would be really helpful, thank you!

**Comment by johannesostner** [comment]
Hello!

I am aware of numpy giving "mean of empty slice" warnings for cell types with an inclusion probability of 0. These are no errors though (and also no reason for concern), and I think you might have a different problem. Unfortunately I can not give you an answer without any further information. Could you please provide

- the exact functions you are calling
- the whole error message that Python gives you
- the data types of your metadata (especially the treatment condition) (`<data>.obs.dtypes`)

Thank you!

**Comment by miligeo18** [comment]
Hi! 

- The function I am calling that is giving me the error is: .sample_hmc() (following the conversion of my table of cell counts to anndata and running the mod.CompositionalAnalysis() function)

- This is the error message I am receiving from python: 

MCMC sampling finished. (23.681 sec)
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-cf5190d325d2> in <module>
      1 # Run MCMC
----> 2 sim_results = model_obj_iggvsnat.sample_hmc()

~/opt/anaconda3/lib/python3.8/site-packages/sccoda/model/dirichlet_models.py in sample_hmc(self, num_results, num_burnin, num_adapt_steps, num_leapfrog_steps, step_size)
    301 
    302         # apply burn-in
--> 303         states_burnin, sample_stats, acc_rate = self.get_chains_after_burnin(states, kernel_results, num_burnin,
    304                                                                              is_nuts=False)
    305 

~/opt/anaconda3/lib/python3.8/site-packages/sccoda/model/dirichlet_models.py in get_chains_after_burnin(self, samples, kernel_results, num_burnin, is_nuts)
    220 
    221             # Calculate acceptance rate
--> 222             p_accept = sum(acceptances) / acceptances.shape[0]
    223         print('Acceptance rate: %0.1f%%' % (100 * p_accept))
    224 

ZeroDivisionError: division by zero

- My data type for the metadata is 'object' 

thank you!

**Comment by johannesostner** [comment]
Ok, something goes wrong while calculating the acceptance rate of the HMC sampling process. To my knowledge this could have two causes:

1. The output of the HMC sampling is not of the form expected by scCODA. The latest versions of tensorflow (2.4.x) and tensorflow-probability (0.12.x) introduced some breaking changes that I have not been able to consistently reproduce. Please make sure that you have the right package versions of tensorflow (==2.3.2) and tensorflow-probability (==0.12.0) installed.
2. The HMC sampling procedure failed entirely and produced a chain where no proposal was accepted. In that case, you may want to increase the length of the generated chain, by changing the `num_results` parameter, e.g. `sample_hmc(num_results=100000)`

**Comment by miligeo18** [comment]
Thank you for these insights! 

When I installed tensorflow==2.3.2 and tensorflow-probability==0.12.0, I received the following error when running the line
from sccoda.util import comp_ana as mod : 

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.4; Detected an installation of version 2.3.2. Please upgrade TensorFlow to proceed.

I was able to get results when increasing the length of the generated chain initially, but got the same "division by zero" error when I changed the reference cell type. Is there a threshold for how many counts there must be of a cell type in order to successfully use it as a reference cell type?

**Comment by johannesostner** [comment]
The correct version of tensorflow is 0.11.0 - I am sorry for that mistake. You can also find the necessary versions of all packages in the `requirements.txt` file in the repository.

**Comment by johannesostner** [comment]
Generally, there are no requirements to a reference cell type. I would advise against taking a reference with many zero entries (more than 10% of all samples) though.
In the latest version (0.1.2), You can also automatically select a reference by setting `reference_cell_type="automatic"`.

**Comment by miligeo18** [comment]
After updating it to the correct version tensorflow-probability everything seems to be working now. 

Thank you so much for all of your help!!
