### ISSUE TITLE
add_dots parameter not respecting hue_order arg in boxplot

### ISSUE THREAD

**Issue by fbrundu** [theislab/scCODA#32]
Hi,

I'm using the boxplot wrapper from this package to plot differences in proportions.
I noticed that, if I want to specify the `hue_order` of the `feature_name` categories with:

```
viz.boxplots(
    data, feature_name='genotype', dpi=150, cmap=['#393e41', '#ca3c25'],
    figsize=(10,10), args_boxplot={'hue_order': ['Control', 'Case']},
    add_dots=True,
)
```

the dots added by `add_dots=True` do not respect the `hue_order` parameter but they default to the original ordering (images attached, without and with custom `hue_order`).

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/697622/120689319-0c809000-c472-11eb-9f5b-d8d631200521.png">

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/697622/120689422-15716180-c472-11eb-83bf-1f0d4fb7a6a1.png">

---

I'm using `scCODA==0.1.2.post1`.

Thanks

**Comment by fbrundu** [comment]
I just noticed that the same `hue_order` should be defined in `args_swarmplot`. Probably it would be helpful to raise a warning or automatically set the same `hue_order` on both?

**Comment by johannesostner** [comment]
Hi, thanks for your feedback!
This is definitely not intended and I will have a look into this

**Comment by johannesostner** [comment]
Fixed the issue on the current development branch, the changes will be included in the next release!

**Comment by fbrundu** [comment]
Looks good :) thank you very much!
