### ISSUE TITLE
Including Bad Cells in Model

### ISSUE THREAD

**Issue by kanefos** [theislab/scCODA#35]
Hi there,

I'm greatly appreciative of the way scCODA models changes in whole-sample composition versus univariate cell counts. 

This in mind, if I am working with a dataset with a prevalence of stress (say, 5-10% of the cells in every sample fail QC), should I include these cells in final compositional abundance testing? Seeing as they are part of overall sample composition. I do know that stress was unfortunately more prevalent in one condition. And yes, I know avoiding this initially would have been much more preferable but here we are.

Thanks!
Kane

**Comment by mbuttner** [comment]
Hi Kane,

thank you for your positive feedback! 
That's an interesting question! I have been working on a similar setting, where cells in one condition tend to be more stressed. I would think that if the stressed cells are distributed equally across cell types, it is safe to exclude them from the compositional analysis as they should not affect the overall composition in the stressed condition. On the other hand, if you observe that a certain cell type is predominantly affected by your stress condition, I would consider this as a biologically relevant effect, which contributes to the change in cell type composition and should be considered in the analysis. 

Best,
Maren

**Comment by kanefos** [comment]
Hi Maren,

Thanks for the useful reply! I'm also of the opinion that stress should be randomly distributed across a dataset (even if samples are composed of mixed cell types, i.e. lyphoid/myeloid, I don't think it's too large an assumption). 

My only follow-up query would be regarding where, by chance, a cell type present to a great extent in condition which had more stress, such as a different protocol in the control, is therefore more adversely affected by QC. I will run both and if come up with anything interesting will share.

Thanks again!
