### ISSUE TITLE
WARNING:tensorflow:@custom_gradient grad_fn has 'variables' in signature

### ISSUE THREAD

**Issue by Elhl93** [theislab/scCODA#40]
Hi, 

many thanks for the package! After running ".sample_hmc()" I receive a warning: 

WARNING:tensorflow:@custom_gradient grad_fn has 'variables' in signature, but no ResourceVariables were used on the forward pass.

After investigating the results with arviz, I observed that sample-stats -> chain only contains level 0 (I have multiple conditions, but I tried with 2 and 3, one being the reference), I furthermore could not find a 'mu' and 'tau' in the results with az.summary(all_results, var_names=['mu', 'tau'], filter_vars="regex"). Previously I ran:

mod.CompositionalAnalysis(CCM_GMEAN_SUB, formula="C(TREATMENT_COLNAME, Treatment('ELEMENT1_IN_TREATMENT_COLNAME'))", 
                                          reference_cell_type="CELL_TYPE_REFERENCE"). 

Thanks for your thoughts.

**Comment by johannesostner** [comment]
Hi, thanks for using scCODA!
This is an issue we have not encountered previously, but is definitely not intended. Unfortunately I can't tell the cause of it from the information you provide.

Could you please share:
- The versions of packages (at least scCODA, tensorflow, tensorflow-probability and arviz) that you use
- some info on your data: The dimensions of `CCM_GMEAN_SUB.X`, a description of your covariate `CCM_GMEAN_SUB.obs["TREATMENT_COLNAME"]`

Please also make sure that your reference cell type is actually in the data.

Thanks!
