### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by dawe** [theislab/scCODA#42]
Hi all, I wanted to follow the examples suggested at the end of `README.md` page but rendering of html pages is gibberish (see [here](https://sccoda.readthedocs.io/en/latest/Modeling_options_and_result_analysis.html)).
![Screenshot 2021-11-26 at 15 22 44](https://user-images.githubusercontent.com/121868/143594963-fe74478d-6261-42ee-a54c-db7e75f2e091.png)

**Comment by johannesostner** [comment]
Hi!
Thanks for reporting this issue. The rendering of the tutorial notebooks should be fixed now. Please be aware that the google colab and nbviewer buttons at the top do not work right now. If the issue still persists for you, you can also view the notebooks [here](https://github.com/theislab/scCODA/tree/master/tutorials).

**Comment by dawe** [comment]
Thanks!
