### ISSUE TITLE
Zero Fold-change in scCODA results

### ISSUE THREAD

**Issue by RachellyN** [theislab/scCODA#45]
Hi,
I have ran scCODA on a few sub-clusterings, and in many of them I get zero fold-change in the summary of scCODA run, though there is clearly a non-zero fold-change between the contions.
Attached is one example of cell counts per condition per cluster and the frequency graph for this data.

What I ran is:
```
    counts_per_sample = pd.read_csv("counts.csv")
    counts_adata = dat.from_pandas(counts_per_sample, covariate_columns=['Condition'])
    model = mod.CompositionalAnalysis(counts_adata, formula=f"C('Condition', Treatment('ctl'))", reference_cell_type='automatic')
    sim_results = model.sample_hmc()
    sim_results.summary()
```
The full output is also attached.

Thanks for your help!
Rachelly.

[counts.csv](https://github.com/theislab/scCODA/files/7847869/counts.csv)
[output.txt](https://github.com/theislab/scCODA/files/7847949/output.txt)
![proportions](https://user-images.githubusercontent.com/35488838/148974422-4364ea32-ebc7-470a-a58c-ad64649d02a4.png)

**Comment by johannesostner** [comment]
Hi,
thanks for trying out scCODA!

One of the main features of scCODA is that it automatically selects only cell types that have a large enough change in abundance to be differentially abundant. All other (cell type-condition) associations will have an effect (final parameter) of 0.
The strictness of this selection process is related to the expected false discovery rate, and can be adjusted, even after the sampling process, via `sim_results.set_fdr(est_fdr=xxx)`. The default FDR value is 0.05, increasing it will give you more credible associations at the cost of higher uncertainty.

**Comment by RachellyN** [comment]
Thanks for your response johannesostner.
I actually menat the log2(fold-chnage) mentioned in the results and not the final parameter.
This is taken from the output file attached to the original message:

                                                log2-fold change  
Covariate                            Cell Type                    
C(Condition, Treatment('ctl'))[T.GD] 1                       0.0  
                                     2                       0.0  
                                     3                       0.0  
                                     4                       0.0  
                                     5                       0.0  
                                     6                       0.0  
                                     7                       0.0  
C(Condition, Treatment('ctl'))[T.HT] 1                       0.0  
                                     2                       0.0  
                                     3                       0.0  
                                     4                       0.0  
                                     5                       0.0  
                                     6                       0.0  
                                     7                       0.0

**Comment by johannesostner** [comment]
Hi Rachelly,
I see what you mean now. The log2-fold change in the results table is not calculated from the data, but from the inferred parameters as the change between the "expected sample" columns of the intercept (control group) and effects (case group for each covariate), to give an idea of the magnitude of the detected credible population shifts. 
Therefore, if all effects ("Final parameter") are 0, i.e. no credible changes were detected, the log2-fold change will also be 0, as the expected samples with and without the covariate are the same.

I hope that this clears up your confusion. I also adjusted the wording in the ["Result interpretation" section](https://sccoda.readthedocs.io/en/latest/getting_started.html#Result-interpretation) of the tutorial to point out the case with no credible changes again.
