### ISSUE TITLE
Stacked barplot not working

### ISSUE THREAD

**Issue by learning-MD** [theislab/scCODA#50]
Hi, I'm able to get an appropriate/accurate boxplot with viz.boxplots(). However, when I try viz.stacked.barplot() with the same input, I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-7b7aa02bf827> in <module>
----> 1 viz.stacked.barplot(data_scanpy, feature_name = "Condition")
      2 plt.show()

AttributeError: module 'sccoda.util.data_visualization' has no attribute 'stacked'
```

Any help would be appreciated. Thanks.

**Comment by johannesostner** [comment]
Hi!
There is no function called `stacked.barplot` in 'sccoda.util.data_visualization'. I think you are looking for `stacked_barplot`
