### ISSUE TITLE
col_wrap in utils.visualization.boxplots

### ISSUE THREAD

**Issue by c-westhoven** [theislab/scCODA#55]
Hi scCODA team,

Line 265 in data_visualization gives an error when running boxplots with plot_faucets = True.
The issue is in the col_wrap parameter for the sns function. np.floor gives a float, not an int, which leads to an error in the FacetGrid function.

**Comment by johannesostner** [comment]
Hi @c-westhoven,
thanks for pointing this out! This bug will be fixed in the next update!
