### ISSUE TITLE
P value (FDR) and interpretation of "Final Parameter"

### ISSUE THREAD

**Issue by grimwoo** [theislab/scCODA#61]
thanks for the development of the great scCODA.

here, i wonder how to get the P value (or FDR) of the analysis.

And could you please teach me how to interpret the "Final Parameter". For example, if a cell type, "Endothelial cell", got 2.007198 as "Final Parameter".

**Comment by johannesostner** [comment]
Hi @grimwoo!

scCODA is a fully Bayesian model, therefore it is not possible to compute p-values. You can, however, adjust the desired FDR in the results object via `result.set_fdr`. See "Adjusting the False Discovery Rate" in our [tutorial](https://sccoda.readthedocs.io/en/latest/getting_started.html).

The "Final parameter" is not straightforward to interpret. If it is 0, the effect is not credible, and if it is different from 0, we have a credible increase (greater than 0) or decrease (less than 0) of the respective cell type. 
The exact numerical value is dependent on the value of the intercept parameters, among others, though. Therefore, we give the log-fold change in the summary, which shows how the cell population shifts under the condition(s). You can also find more on this in the tutorial.

In your example, the Endothelial cells show a credible increase.

**Comment by grimwoo** [comment]
Thank you for your quick response! @johannesostner
