### ISSUE TITLE
loading data with dat.from_scanpy 

### ISSUE THREAD

**Issue by HosseinMousavi** [theislab/scCODA#65]
Hi. I transformed my dataset from the seurat object to the anndata (using scanpy).
I have two samples in my dataset.
I am dealing with loading data from scanpy to scCODA format.
what is covariate_df exactly? in the tutorial, I have not seen the real example of covariate_df. it was the simulated version.

Thanks,

**Comment by HosseinMousavi** [comment]
It was solved!

Thanks!

**Comment by yamihn** [comment]
hi, how did you solved the issue?
