### ISSUE TITLE
access sim_results.summary() for further analysis in R

### ISSUE THREAD

**Issue by dwendisch** [theislab/scCODA#71]
Hi!
My Python knowledge is very superficial. I managed to create sim_results.summary() of my analysis. Now I would like to continue my analysis in R. However I don't quite know how to deal with a type <class 'sccoda.util.result_classes.CAResult'>.

Could you help me with how I could store the results in a tabular format in a .csv that I can read into my R environment?

All the best and thank you!

**Comment by johannesostner** [comment]
Thanks for using scCODA!
Since you found your answer, I'll close this issue
