### ISSUE TITLE
scCODA p-values?

### ISSUE THREAD

**Issue by katieaney** [theislab/scCODA#72]
Hi, 

This is question, not an issue. 

I am running scCODA compositional analysis followed by HMC sampling. I can see the result summary and extended summary as detailed in the documentation. I can then use Arviz to plot traces and kernel density estimates. My question is - how might I estimate the p-values for the fold changes that are calculated using scCODA? I tried calculating the p-val using the HPD interval, but I'm unable to find a package that can do this (tried Arviz and PyMC3). Is scCODA able to do this? 

Any suggestions or direction would be appreciated.

The code I'm using, if that is helpful:
model_R = mod.CompositionalAnalysis(R, formula="Condition", reference_cell_type="automatic") 
sim_results = model_R.sample_hmc()
sim_results.summary_extended(hdi_prob=0.9)

**Comment by johannesostner** [comment]
Hi @katieaney,
scCODA performs parameter inference via Bayesian methods (HMC sampling). These methods, opposed to frequentist hypothesis testing, do not produce p-values. You can compare the confidence of effects via other measures, e.g. the inclusion probability (see #47 ), which is also used to get the credible effects at different FDR values. 

The fold-changes in the summary are simply calculated by looking at the difference of expected compositions with/without the respective condition active, using the inferred parameters
