### ISSUE TITLE
Replace sklearn dependency with scikit-learn

### ISSUE THREAD

**Issue by radutanasa** [theislab/scCODA#73]
The sklearn dependency has been deprecated. Currently, the installation of scCODA fails unless the variable SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL is set to true. 

See more here: https://github.com/scikit-learn/sklearn-pypi-package

**Comment by johannesostner** [comment]
Hi @radutanasa,
thanks for spotting this. I removed sklearn from the dependencies list, as it is not required for scCODA anymore (simply forgot to remove it from the dependencies list).
