### ISSUE TITLE
conda compatibility

### ISSUE THREAD

**Issue by Nusob888** [theislab/scCODA#75]
Hi, 

Is there any possibility of submitting sccoda to conda?

I am having a lot of compatibility issues with sccoda compatibility. It appears to break my scanpy installations when installed via pip.

Many thanks for your consideration

**Comment by johannesostner** [comment]
Hi @Nusob888!
We've recently released a complete reimplementation of scCODA as part of the scverse package [pertpy](https://github.com/theislab/pertpy). 
Please check it out - you will hopefully run into less compatibility issues there!

**Comment by Nusob888** [comment]
Hi thanks for the feedback, 

sadly, still dependency issues and I am only using scverse tools in my conda environment. It would be great if the scverse packages could all have conda implementations to avoid conflicts caused by pip and conda if possible.

**Comment by johannesostner** [comment]
That's unfortunate - I'm also using conda environments and never had any problems with installing scCODA or pertpy via pip.  
Is there a specific dependency that causes these compatibility issues? What error message do you get?

**Comment by Zethson** [comment]
@Nusob888 please open an issue at pertpy if you're having installation troubles. Happy to help you over there.
