### ISSUE TITLE
Questions about generalizability to other NGS datasets

### ISSUE THREAD

**Issue by jolespin** [theislab/scCODA#77]
I'd like to use this for two separate datasets: 
* Dataset 1 contains human scRNA-seq where each row is a single-cell and each column is a feature.  I also have ERCC spikes
* Dataset 2 contains metagenomics sequencing where each row is a sample and each column is a taxa.  I don't have any controls here. 

My questions: 
* For dataset 1, do I sum up the ERCC spikes to include as their own column and use this as the reference? 
* For dataset 2 where I don't have a reference, what do you recommend? 
 
In both of these scenarios, I'd like to measure differential abundance for components (i.e., features) within my compositions (e.g., samples or single-cells).

**What would you recommend?**

**Comment by johannesostner** [comment]
Hi @jolespin,

thank you for your questions!
Regarding dataset 1, I wonder what you mean by "features". Are these gene expressions? For those, I would recommend other methods like DeSeq2 or EdgeR - their normalizations will have similar effects as accounting for compositionality, but are much more computationally efficient.
If you want to use scCODA, you can either sum up all spikes and treat them as one reference component, or just use one ERCC spike as the reference - both are feasible. I would opt for the procedure that gives you a better estimate of the total sum of features in the samples. Also, your reference should be present in every sample (cell in your case)

Regarding dataset 2, we have an automatic reference selection heuristic implemented (`reference_cell_type="automatic"`). With this, you will get a reference that has low dispersion over your samples, which is often a good candidate. Alternatively, you can also iterate over all possible references and look at cumulative selections of taxa (like at the end of our [advanced tutorial](https://sccoda.readthedocs.io/en/latest/Modeling_options_and_result_analysis.html))
