### ISSUE TITLE
AttributeError: module 'arviz' has no attribute 'data'

### ISSUE THREAD

**Issue by jhong26** [theislab/scCODA#78]
Hi,
I am trying to work through the tutorial but I am getting stuck at the very beginning when I try to run the command below. Any input would be much appreciated. Thank you.

from sccoda.util import comp_ana as mod

output:

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_48124/3275336626.py in <module>
----> 1 from sccoda.util import comp_ana as mod

~/.local/lib/python3.9/site-packages/sccoda/util/comp_ana.py in <module>
      8 
      9 from anndata import AnnData
---> 10 from sccoda.model import scCODA_model as dm
     11 from typing import Union, Optional
     12 

~/.local/lib/python3.9/site-packages/sccoda/model/scCODA_model.py in <module>
     14 import tensorflow_probability as tfp
     15 
---> 16 from sccoda.util import result_classes as res
     17 from typing import Optional, Tuple, Collection, Union, List
     18 

~/.local/lib/python3.9/site-packages/sccoda/util/result_classes.py in <module>
     16 
     17 
---> 18 class CAResultConverter(az.data.io_dict.DictConverter):
     19     """
     20     Helper class for result conversion into arviz's format

AttributeError: module 'arviz' has no attribute 'data'

**Comment by johannesostner** [comment]
Hi @jhong26,
this looks like an import error with arviz. Could you please check which version of arviz is installed in your environment?

`import arviz`
`arviz.__version__`
