### ISSUE TITLE
Additive model with batch 

### ISSUE THREAD

**Issue by flde** [theislab/scCODA#85]
Hello, 

Many thanks for developing scCODA (so far it works with R + reticulated which is cool). We want to investigate the treatment effect on the cell type composition between patients. However, some samples were processed with a different protocol which also influences the enrichment of specific cell populations (non-immune cells) which would usually serve as a reference group. 

Do I understand correctly that when using the additive formula protocol + treatment the beta for treatment should be free of the effects from protocol and vice versa? I guess so but highly appreciate if you could confirm the general idea. 

All the very best, 
Florian

**Comment by johannesostner** [comment]
Hi @flde!
The formula in scCODA works just like a linear regression model. By adding a term for the protocol, scCODA will try to find significant differences between the protocols. However, non-significant effects will be deselected (set to 0) in the process. Thus, adding the protocol term will only adjust for stronger shifts in the composition and is not a strict adjustment.

We don't support adding covariates without effect selection in scCODA at this point, but including the protocol as you described can at least give you an adjustment if the protocol effects are severe. Just make sure that you select a cell type as the reference that is not effected by the protocols.

**Comment by flde** [comment]
Hi @johannesostner, 

Thank you so much for the insights, the information is very helpful! Will have a closer look at the code but the results make very much sense already and I think compositional analysis just needs always cautions interpretation in this setting. 

All the very best, 
Florian
