### ISSUE TITLE
mixed effect model

### ISSUE THREAD

**Issue by t-a-m-i** [theislab/scCODA#87]
Hi, 
I´m trying to implement scCODA for my scRNAseq data set of 6 different donors for which I have control and treatment data each. I´d like to see the effect of the treatment, but want to always compare control vs. treatment within each donor and handle the donors as random effects in a mixed effects model. However, I can´t seem to figure out how to adjust the formula. Any help appreciated!

**Comment by johannesostner** [comment]
Hi!
Unfortunately, mixed effect models are not implemented for scCODA. Some alternatives would be to encode the donor info as a categorical variable or to do a donor-wise analysis, if that is an option for your study design
