### ISSUE TITLE
Use the model with multiple covariants including numeric ones?

### ISSUE THREAD

**Issue by RunyuXia** [theislab/scCODA#88]
Hi! I was wondering if the model could be used with three categorical variables (sex, genotype) as well as a numeric variable (age) at the same time？

**Comment by johannesostner** [comment]
Hi!
Yes, scCODA supports the use of multiple variables from different types. You have to make sure that your numeric variables are normalized, though. Otherwise, their effects might become very small, which will lead to them being dropped in the variable selection process
