### ISSUE TITLE
Usage without replicates ?

### ISSUE THREAD

**Issue by divyanshusrivastava** [theislab/scCODA#90]
Hi. 
I tried using the package on my data, where I have control and case conditions with only one replicate each. 
The model returned no significant changes, and I was wondering if this is because of lack of replicates. I followed [this](https://sccoda.readthedocs.io/en/latest/getting_started.html) tutorial.

Can you comment on how to use the package when one has no replicates ?
Thanks

**Comment by johannesostner** [comment]
Hi @divyanshusrivastava!
It's very likely that the lack of replicates is one reason why you don't get any significant results. As with any other statistical model or test, scCODA's uncertainty depends on the number of replicates. If there's very few, only very strong differences wil be reliably detected.

**Comment by divyanshusrivastava** [comment]
Thanks for the response :) 
Closing this issue
