### ISSUE TITLE
How to compare multiple groups with sccoda

### ISSUE THREAD

**Issue by karenlawwc** [theislab/scCODA#94]
Hi, I am wondering if I have three groups of variables I want to compare cell composition using sccoda, what would be the best way to do it? Since using different groups as reference would result in different differential expression result.

What would be the best practice you would recommend? Subsetting the data and only comparing two groups at the same time? 

Thanks!

**Comment by johannesostner** [comment]
Hi @karenlawwc!

I'm not 100% sure what the term "reference" in your question refers to. Do you mean the categories in your composition (cell types) or the levels of a covariate variable (e.g. control - condition 1 - condition 2)?

**Comment by wdg118** [comment]
Hi @johannesostner,

I have a similar issue, I run:

`# Setup
import importlib
import warnings
import anndata as ad
import pandas as pd
import matplotlib.pyplot as plt
import scanpy as sc

from sccoda.util import comp_ana as mod
from sccoda.util import cell_composition_data as dat
from sccoda.util import data_visualization as viz

# Suppress warnings and set verbosity
warnings.filterwarnings("ignore")
sc.settings.verbosity = 3
sc.logging.print_header()

# File paths - update these to the actual locations of your files
files = {
    "WT": "granger_adata_wt_20231208_with_genotype_MMC_cortex_only_final_projected_data_by_region_name.h5ad"
    "HT_1": "granger_adata_ht_20231213_with_genotype_MMC_cortex_only_final_projected_data_by_region_name.h5ad",
    "HT_2": "granger_adata_ht_20240116_with_genotype_MMC_cortex_only_final_projected_data_by_region_name.h5ad",
    "KO_1": "granger_adata_ko_20231223_with_genotype_MMC_cortex_only_final_projected_data_by_region_name.h5ad",
    "KO_2": "granger_adata_ko_20240313_with_genotype_MMC_cortex_only_final_projected_data_by_region_name.h5ad",
}

# Assuming each h5ad file corresponds to a distinct sample and not individual cells
adata_list = []
conditions = []

for condition, filepath in files.items():
    adata = ad.read_h5ad(filepath)
    # Remap genotype conditions
    if condition.startswith("HT"):
        adata.obs['Condition'] = "HT_all"
    elif condition.startswith("KO"):
        adata.obs['Condition'] = "KO_all"
    else:
        adata.obs['Condition'] = "WT"
    adata.obs['cell_type'] = adata.obs['subclass_name_h']
    adata_list.append(adata)
    conditions.append(adata.obs['Condition'][0])  # Assuming consistent condition per file

# Create a DataFrame for covariates that aligns with the number of samples
cov_df = pd.DataFrame({"Condition": conditions})

# Use from_scanpy_list to integrate Anndata objects
data_composed = dat.from_scanpy_list(
    adata_list,
    cell_type_identifier="cell_type",
    covariate_df=cov_df
)

# Now proceed with the analysis as before
model = mod.CompositionalAnalysis(data_composed, formula="Condition", reference_cell_type="automatic")
sim_results = model.sample_hmc()
print(sim_results.summary())

viz.boxplots(data_composed, feature_name="Condition")
plt.show()
print(sim_results.credible_effects())`

I only see the KO_all to WT comparsison and for some reason HT_all goes missing in the analysis. How do I fix this?

Thanks!

**Comment by johannesostner** [comment]
Hi @wdg118!
Each pairwise comparison works just as a normal scCODA model (Final parameter != 0 --> credible effect). For comparing runs of scCODA on different pairs of conditions, you can only get a qualitative comparison through the final parameter. The numerical vaues are not easily comparable. Instead, you can look at the log-fold change in the summary. Those are comparable quantitatively as well.

**Comment by wdg118** [comment]
Hi @johannesostner ,

Thanks for clarifying this. I appreciate it! Also I'm assuming the model accounts and corrects for multiple comparisons? I believe this can be inferred from the fact you can change the FDR right ?

Thanks!

**Comment by johannesostner** [comment]
Exactly! You can set the FDR to a desired level and the model will select the credible effects based on their bayesian inclusion probability, controlling for multiple comparisons. You can read more about that in the paper if you want.
