### ISSUE TITLE
Using continuous variables yield weird results.

### ISSUE THREAD

**Issue by Marwansha** [theislab/scCODA#96]
Hi,

I'm experiencing issues with scCODA when analyzing the effect of a continuous covariate (CMV serostatus) as opposed to a categorical one. When I categorize CMV serostatus as positive/negative based on a threshold, the results align with known effects on cell types. However, using continuous values yields nonsensical results, showing a credible effect on all cell types with odd final parameters and LFC that don't reflect the actual effect.

Below are examples of the CMV covariate analysis. All cell types, except the reference, appear to be true with strange final parameters and LFC.
![image](https://github.com/theislab/scCODA/assets/144441199/f6b3684b-e231-4cea-8125-b1062f425ba9)

When I categorize the same data based on the threshold, the results make sense and match a simple linear regression analysis. I also checked the effect of another continuous variable, age, and the results were similarly illogical. But when I divided the ages into four categorical groups, the output was normal and consistent with known age effects on cell proportions.

**Comment by johannesostner** [comment]
Hi @Marwansha!
What range is your covariate in? You should make sure that your continuous covariates are normalized before applying scCODA

**Comment by Marwansha** [comment]
Thanks a lot for your response,

Actually it's not a matter of normalisation 

For example checking the effect of age( in years) as a continuous variable , I observe same thing. 
Where the output from scCoda from categorical age variable perfectly match   the effects detected using linear regression and the literature  But when I use continuous variable in the scCoda formula , the output doesn't make sense not even from the final parameter values point of view.



I can share the data by email if you don't mind taking a look, I have compositional cell type counts dataframe with the meta data  columns for age as a continuous variable and another time as ( age groups) / same for cmv serostatus ( positive / negative) or the actual continuous values.


Thanks a lot in advance

**Comment by johannesostner** [comment]
Hmmm, that's strange. Are you using only the continuous covariate, or are you including it in a formula together with other covariates?
Could you also maybe share the extended summary output when using a continuous covariate? Either as a screenshot or per email
