### ISSUE TITLE
How to plot the final result?

### ISSUE THREAD

**Issue by mainharryHR** [theislab/scCODA#98]
Dear team,

Thanks for the great package

I believe I have already generate all the comparisons. But when I try to plot, I only can see the one comparison, but not able to plot other comparisons.  `pt.pl.coda.effects_barplot(sccoda_data_control, "coda", "Cancer")
plt.show()`

`AnnData object with n_obs × n_vars = 24 × 15
    varm: 'intercept_df', 'effect_df_Cancer[T.No]', 'effect_df_Cancer[T.CRC]', "effect_df_C(Cancer, Treatment('Control'))[T.No]", "effect_df_C(Cancer, Treatment('Control'))[T.CRC]", "effect_df_C(Cancer, Treatment('No'))[T.Control]", "effect_df_C(Cancer, Treatment('No'))[T.CRC]"
`
<img width="588" alt="Screenshot 2024-05-20 at 10 06 16" src="https://github.com/theislab/scCODA/assets/164251298/4e3eff46-7413-422f-b8e5-00b93ddf75b6">
Any comments are welcome!

**Comment by johannesostner** [comment]
Hi @mainharryHR,
this is the repository for scCODA's initial implementation. You are referring to a functionality from the reimplementation in the pertpy package (https://github.com/theislab/pertpy).
Please ask your question over there!
